version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: memes_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data

  app:
    build:
      context: .
      args:
        - SERVICE=app
    environment:
      DATABASE_URL: postgresql://user:password@db/memes_db
    ports:
      - "80:80"
    depends_on:
      - db
      - minio

  media_service:
    build:
      context: .
      args:
        - SERVICE=media
    ports:
      - "8000:8000"
    depends_on:
      - minio

volumes:
  postgres_data:
  minio_data: