FROM python:3.10

# Установка зависимостей
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

# Копирование приложения
COPY ./media_service /app/media_service

# Установка рабочей директории
WORKDIR /app

# Команда для запуска приложения
CMD ["uvicorn", "media_service.main:app", "--host", "0.0.0.0", "--port", "8000"]